#!/bin/bash
if [[ $# -ne 2 ]]; then
    echo "Call with: rocketChatMessage \$CHANNEL \$MESSAGE"
    exit 1
fi
CHANNEL=$1
MESSAGE=$2
API_URL="https://rocket.belvederetrading.com/api/v1"
TMP="$(mktemp)"

echo "Password:"
read -s PASSWORD
curl $API_URL/login -d "username=ehiggins&password=$PASSWORD" > $TMP
cat $TMP
ID=$(cat $TMP | jq -r '.data.userId')
AUTH=$(cat $TMP | jq -r '.data.authToken')

JS='{ "channel" : "", "text": ""}'
JS=$(echo $JS | jq ".text=\"$MESSAGE\"" | jq ".channel=\"$CHANNEL\"")
echo $JS

AUTH_HEADER="X-Auth-Token: $AUTH"
AUTH_ID="X-User-Id: $ID"
curl -H "$AUTH_HEADER" \
     -H "$AUTH_ID" \
     -H "Content-Type: application/json" \
     $API_URL/chat.postMessage \
     -d "$(echo $JS)"

curl -H "$AUTH_HEADER" \
     -H "$AUTH_ID" \
     $API_URL/logout
