#!/usr/bin/env osascript

tell application "Spotify"
  if it is running then
    set vol to get sound volume
    set newvol to vol + 5
    if newvol <= 100 then
      set sound volume to newvol
    else
      set sound volume to 100
    end if
  end if
end tell
